language: php
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql
  - mongodb

before_script:
  - pecl install mongodb
  - composer install
  - composer require olive-cms/udms-json
  - composer require olive-cms/udms-mysql
  - composer require olive-cms/udms-mongodb

script:
  - chmod +x ./test/run
  - ./test/run -y
