language: php
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

services:
  - mysql
  - mongodb

before_script:
  - pecl install mongodb
  - composer install

script:
  - chmod +x ./test/run
  - ./test/run -y
