language: php
dist: trusty
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

services:
  - mysql
  - mongodb

before_script:
  - [[ "$TRAVIS_PHP_VERSION" == "7.2" ]] || pecl install mongodb
  - composer install

script:
  - chmod +x ./test/run
  - ./test/run -y
